require:
- rubocop-rake
- rubocop-rspec

AllCops:
  NewCops: "enable"
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 6
